language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  - pip
install:
  - pip install -r requirements.txt

script:
  - pylint --rcfile=.pylintrc monitoring.py tools notification probes tests
  - pycodestyle monitoring.py tools notification probes tests
  - python -m unittest discover tests -v
